stats_to_aggregate = [
    "kills",
    "deaths",
    "assists",
    "dpm",
    "damageshare",
    "damagetakenperminute",
    "wpm",
    "wcpm",
    "vspm",
    "earned gpm",
    "cspm",
    "golddiffat10",
    "xpdiffat10",
    "csdiffat10",
    "golddiffat15",
    "xpdiffat15",
    "csdiffat15",
    "golddiffat20",
    "xpdiffat20",
    "csdiffat20",
    "golddiffat25",
    "xpdiffat25",
    "csdiffat25",
]